services:

  api:
    image: golang:latest
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:/app
    working_dir: /app
    command: go run services/api/main.go
    environment:
      PUBSUB_EMULATOR_HOST: "pubsub:8085"
    depends_on:
      - pubsub
    networks:
      - benefex_task

  pubsub:
    image: google/cloud-sdk:latest
    platform: linux/amd64
    ports:
      - "8085:8085"
    command: "gcloud beta emulators pubsub start --host-port 0.0.0.0:8085"
    networks:
      - benefex_task

networks:
  benefex_task: