version: '3.8'

services:

  api:
    image: golang:1.17
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:/app
    working_dir: /app
    command: go run cmd/api/main.go

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
